version: "3"
services:
  app:
    build: .
    image: ghcr.io/joyalzzy/wagalorant:latest
    container_name: wagalorant
    command: node build/main.js
    env_file:
    - .env
    ports:
      - 3000:3000
