name: build image


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-multi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.PAT_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/joyalzzy/wagalorant:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max


